config/routes.rb
Rails.application.routes.draw do
  resources :eventos
  resources :alojamientos
  resources :arrendatarios
  resources :estudiantes
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alojamiento.rb
class Alojamiento < ApplicationRecord
belongs_to  :Arrendatario
end

app/controllers/alojamientos_controller.rb
class AlojamientosController < ApplicationController
  before_action :set_alojamiento, only: [:show, :edit, :update, :destroy]

  # GET /alojamientos
  # GET /alojamientos.json
  def index
    @alojamientos = Alojamiento.all
  end

  # GET /alojamientos/1
  # GET /alojamientos/1.json
  def show
  end

  # GET /alojamientos/new
  def new
    @alojamiento = Alojamiento.new
  end

  # GET /alojamientos/1/edit
  def edit
  end

  # POST /alojamientos
  # POST /alojamientos.json
  def create
    @alojamiento = Alojamiento.new(alojamiento_params)

    respond_to do |format|
      if @alojamiento.save
        format.html { redirect_to @alojamiento, notice: 'Alojamiento was successfully created.' }
        format.json { render :show, status: :created, location: @alojamiento }
      else
        format.html { render :new }
        format.json { render json: @alojamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alojamientos/1
  # PATCH/PUT /alojamientos/1.json
  def update
    respond_to do |format|
      if @alojamiento.update(alojamiento_params)
        format.html { redirect_to @alojamiento, notice: 'Alojamiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @alojamiento }
      else
        format.html { render :edit }
        format.json { render json: @alojamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alojamientos/1
  # DELETE /alojamientos/1.json
  def destroy
    @alojamiento.destroy
    respond_to do |format|
      format.html { redirect_to alojamientos_url, notice: 'Alojamiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alojamiento
      @alojamiento = Alojamiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alojamiento_params
      params.require(:alojamiento).permit(:tipo, :descripcion, :reglas, :imagen, :sitios_interes, :clasificacion, :calificacion, :cercano)
    end
end

app/helpers/alojamientos_helper.rb
module AlojamientosHelper
end

app/views/alojamientos/_form.html.erb
<%= form_with(model: alojamiento, local: true) do |form| %>
  <% if alojamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alojamiento.errors.count, "error") %> prohibited this alojamiento from being saved:</h2>

      <ul>
      <% alojamiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :alojamiento_tipo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :alojamiento_descripcion %>
  </div>

  <div class="field">
    <%= form.label :reglas %>
    <%= form.text_field :reglas, id: :alojamiento_reglas %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.text_field :imagen, id: :alojamiento_imagen %>
  </div>

  <div class="field">
    <%= form.label :sitios_interes %>
    <%= form.text_field :sitios_interes, id: :alojamiento_sitios_interes %>
  </div>

  <div class="field">
    <%= form.label :clasificacion %>
    <%= form.text_field :clasificacion, id: :alojamiento_clasificacion %>
  </div>

  <div class="field">
    <%= form.label :calificacion %>
    <%= form.text_field :calificacion, id: :alojamiento_calificacion %>
  </div>

  <div class="field">
    <%= form.label :cercano %>
    <%= form.text_field :cercano, id: :alojamiento_cercano %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alojamientos/edit.html.erb
<h1>Editing Alojamiento</h1>

<%= render 'form', alojamiento: @alojamiento %>

<%= link_to 'Show', @alojamiento %> |
<%= link_to 'Back', alojamientos_path %>

app/views/alojamientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alojamientos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descripcion</th>
      <th>Reglas</th>
      <th>Imagen</th>
      <th>Sitios interes</th>
      <th>Clasificacion</th>
      <th>Calificacion</th>
      <th>Cercano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>


    <div class="col s12 m7">
        <h2 class="header">Horizontal Card</h2>
        <div class="card horizontal">
          <div class="card-image">
            <img src="https://lorempixel.com/100/190/nature/6">
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>

    <% @alojamientos.each do |alojamiento| %>
      <tr>
        <td><%= alojamiento.tipo %></td>
        <td><%= alojamiento.descripcion %></td>
        <td><%= alojamiento.reglas %></td>
        <td><%= alojamiento.imagen %></td>
        <td><%= alojamiento.sitios_interes %></td>
        <td><%= alojamiento.clasificacion %></td>
        <td><%= alojamiento.calificacion %></td>
        <td><%= alojamiento.cercano %></td>

        <td><%= link_to 'Show', alojamiento %></td>
        <td><%= link_to 'Edit', edit_alojamiento_path(alojamiento) %></td>
        <td><%= link_to 'Destroy', alojamiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alojamiento', new_alojamiento_path %>

app/views/alojamientos/new.html.erb
<h1>New Alojamiento</h1>

<%= render 'form', alojamiento: @alojamiento %>

<%= link_to 'Back', alojamientos_path %>

app/views/alojamientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @alojamiento.tipo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @alojamiento.descripcion %>
</p>

<p>
  <strong>Reglas:</strong>
  <%= @alojamiento.reglas %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @alojamiento.imagen %>
</p>

<p>
  <strong>Sitios interes:</strong>
  <%= @alojamiento.sitios_interes %>
</p>

<p>
  <strong>Clasificacion:</strong>
  <%= @alojamiento.clasificacion %>
</p>

<p>
  <strong>Calificacion:</strong>
  <%= @alojamiento.calificacion %>
</p>

<p>
  <strong>Cercano:</strong>
  <%= @alojamiento.cercano %>
</p>

<%= link_to 'Edit', edit_alojamiento_path(@alojamiento) %> |
<%= link_to 'Back', alojamientos_path %>