config/routes.rb
Rails.application.routes.draw do
  resources :eventos
  resources :alojamientos
  resources :arrendatarios
  resources :estudiantes
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arrendatario.rb
class Arrendatario < ApplicationRecord
has_many :alojamientos, dependent: :destroy

app/controllers/arrendatarios_controller.rb
class ArrendatariosController < ApplicationController
  before_action :set_arrendatario, only: [:show, :edit, :update, :destroy]

  # GET /arrendatarios
  # GET /arrendatarios.json
  def index
    @arrendatarios = Arrendatario.all
  end

  # GET /arrendatarios/1
  # GET /arrendatarios/1.json
  def show
  end

  # GET /arrendatarios/new
  def new
    @arrendatario = Arrendatario.new
  end

  # GET /arrendatarios/1/edit
  def edit
  end

  # POST /arrendatarios
  # POST /arrendatarios.json
  def create
    @arrendatario = Arrendatario.new(arrendatario_params)

    respond_to do |format|
      if @arrendatario.save
        format.html { redirect_to @arrendatario, notice: 'Arrendatario was successfully created.' }
        format.json { render :show, status: :created, location: @arrendatario }
      else
        format.html { render :new }
        format.json { render json: @arrendatario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arrendatarios/1
  # PATCH/PUT /arrendatarios/1.json
  def update
    respond_to do |format|
      if @arrendatario.update(arrendatario_params)
        format.html { redirect_to @arrendatario, notice: 'Arrendatario was successfully updated.' }
        format.json { render :show, status: :ok, location: @arrendatario }
      else
        format.html { render :edit }
        format.json { render json: @arrendatario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arrendatarios/1
  # DELETE /arrendatarios/1.json
  def destroy
    @arrendatario.destroy
    respond_to do |format|
      format.html { redirect_to arrendatarios_url, notice: 'Arrendatario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arrendatario
      @arrendatario = Arrendatario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arrendatario_params
      params.require(:arrendatario).permit(:nombre, :telefono, :correo, :email, :cc)
    end
end

app/helpers/arrendatarios_helper.rb
module ArrendatariosHelper
end

app/views/arrendatarios/_form.html.erb
<%= form_with(model: arrendatario, local: true) do |form| %>
  <% if arrendatario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arrendatario.errors.count, "error") %> prohibited this arrendatario from being saved:</h2>

      <ul>
      <% arrendatario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :arrendatario_nombre %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :arrendatario_telefono %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :arrendatario_correo %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :arrendatario_email %>
  </div>

  <div class="field">
    <%= form.label :cc %>
    <%= form.text_field :cc, id: :arrendatario_cc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arrendatarios/edit.html.erb
<h1>Editing Arrendatario</h1>

<%= render 'form', arrendatario: @arrendatario %>

<%= link_to 'Show', @arrendatario %> |
<%= link_to 'Back', arrendatarios_path %>

app/views/arrendatarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arrendatarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th>Email</th>
      <th>Cc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arrendatarios.each do |arrendatario| %>
      <tr>
        <td><%= arrendatario.nombre %></td>
        <td><%= arrendatario.telefono %></td>
        <td><%= arrendatario.correo %></td>
        <td><%= arrendatario.email %></td>
        <td><%= arrendatario.cc %></td>
        <td><%= link_to 'Show', arrendatario %></td>
        <td><%= link_to 'Edit', edit_arrendatario_path(arrendatario) %></td>
        <td><%= link_to 'Destroy', arrendatario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arrendatario', new_arrendatario_path %>

app/views/arrendatarios/new.html.erb
<h1>New Arrendatario</h1>

<%= render 'form', arrendatario: @arrendatario %>

<%= link_to 'Back', arrendatarios_path %>

app/views/arrendatarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @arrendatario.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @arrendatario.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @arrendatario.correo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @arrendatario.email %>
</p>

<p>
  <strong>Cc:</strong>
  <%= @arrendatario.cc %>
</p>

<%= link_to 'Edit', edit_arrendatario_path(@arrendatario) %> |
<%= link_to 'Back', arrendatarios_path %>