config/routes.rb
Rails.application.routes.draw do
  resources :eventos
  resources :alojamientos
  resources :arrendatarios
  resources :estudiantes
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :nacionalidad, :telefono, :email, :cc)
    end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante, local: true) do |form| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
      <% estudiante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :estudiante_nombre %>
  </div>

  <div class="field">
    <%= form.label :nacionalidad %>
    <%= form.text_field :nacionalidad, id: :estudiante_nacionalidad %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :estudiante_telefono %>
  </div>

  <div class="input-field col s12">
   <select>
     <option value="" disabled selected>Choose your option</option>
     <option value="1">Option 1</option>
     <option value="2">Option 2</option>
     <option value="3">Option 3</option>
   </select>
   <label>Materialize Select</label>
 </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :estudiante_email %>
  </div>

  <div class="field">
    <%= form.label :cc %>
    <%= form.text_field :cc, id: :estudiante_cc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editing Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table>


  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <div class="col s12 m7">
            <h2 class="header"><%= estudiante.nombre %></h2>
            <div class="card horizontal">
              <div class="card-image">
                <img src="/images/NextBlack.jpg">
              </div>
              <div class="card-stacked">
                <div class="card-content">
                  <p><br>Nombre: <%= estudiante.nombre %></br>
                  <br>Nacionalidad: <%= estudiante.nacionalidad %></br>
                  <br>Telefono: <%= estudiante.telefono %></br>
                  <br>email: <%= estudiante.email %></br>
                  <br>CC: <%= estudiante.cc %></br></p>
                </div>
                <div class="card-action">
                  <%= link_to 'Show', estudiante %>
                  <%= link_to 'Edit', edit_estudiante_path(estudiante) %>
                  <%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </div>
          </div>


      </tr>
    <% end %>
  </tbody>





</table>

<br>

<%= link_to 'New Estudiante', new_estudiante_path %>

app/views/estudiantes/new.html.erb
<h1>New Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estudiante.nombre %>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @estudiante.nacionalidad %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @estudiante.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @estudiante.email %>
</p>

<p>
  <strong>Cc:</strong>
  <%= @estudiante.cc %>
</p>

<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Back', estudiantes_path %>